# This is a basic workflow that is manually triggered

name: Build and Push Dockerfile

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Application name'
        # Default value if no value is explicitly provided
        default: 'hello'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Application version'
        # Default value if no value is explicitly provided
        default: 'latest'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: dockerhub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./practice_projects/project-4
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/app:${{ inputs.version }}
